### PR TITLE
Add AH/DJH as maintainer

### PR DESCRIPTION
**Pull request by Anthchirp**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

### CODE REVIEW

**Comment by Anthchirp** [comment]
@conda-forge-admin, please rerender

**Comment by d-j-hatton** [comment]
I am happy to be added as a maintainer for this package

**Comment by HorstmannA** [comment]
I am also happy to be added as a maintainer for this package

**Comment by Anthchirp** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
